# Copyright 2025 Charles Bouquet
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

services:
  backend:
    container_name: backend
    build:
      context: .
      target: backend
    image: backend:latest
    expose:
      - "8000"
    restart: unless-stopped
    user: python
    volumes:
      - ./backend:/app
      - python_images:/app/Images 
      - backend_data:/app/preprocessing/Data #pour pas ralentir les I/O
      - /app/preprocessing/flattened
      - /app/preprocessing/Raw
    depends_on:
      - init-volumes
  react:
    container_name: react
    build:
      context: .
      target: react
    image: react:latest
    expose:
      - "3000"

    restart: unless-stopped
    user: react
    volumes:
      #- react_build:/output
      - ./frontend:/app
      - /app/node_modules
    #command: sh -c "cp -r /app/build/* /output/"
    environment:
      - WATCHPACK_POLLING=true
    
  
  server:
    container_name: server
    build: 
      context: .
      target: server
    image: server:latest
    restart: unless-stopped
    expose:
      - "80"
      - "3000"
    ports:
      - 8000:8000
      - 80:80
    user: nginx
    volumes:
      - python_images:/app/Images
      - react_build:/app/build

    depends_on:
      - init-volumes
      - react
      - backend
  init-volumes:
    image: busybox #comme pour kubernetes, il faut donner les perms dans le volume avant
    volumes:
      - python_images:/app/Images
    command: 
      sh -c "
        mkdir -p /app/Images &&
        chmod -R 777 /app/Images &&
        chmod -R 777 /app/build
      "



volumes:
  react_build:
  backend_data:
  python_images:
    driver: local
    # driver_opts: pour gagner niveau performances I/O
    #   type: none
    #   device: ./backend/Images
    #   o: bind