services:
  backend:
    container_name: backend
    build:
      context: .
      target: backend
    image: backend:latest
    expose:
      - "8000"
    restart: unless-stopped
    user: python
    volumes:
      - python_images:/app/Images
    depends_on:
      - init-volumes
  react:
    container_name: react
    build:
      context: .
      target: react
    image: react:latest
    expose:
      - "3000"
    restart: no
    user: react
    volumes:
      - react_build:/output
    command: sh -c "cp -r /app/build/* /output/"
    
  
  server:
    container_name: server
    build: 
      context: .
      target: server
    image: server:latest
    restart: unless-stopped
    expose:
      - "80"
      - "3000"
    ports:
      - 8000:8000
      - 80:80
    user: nginx
    volumes:
      - python_images:/app/Images
      - react_build:/app/build

    depends_on:
      - init-volumes
      - react
      - backend
  init-volumes:
    image: busybox #comme pour kubernetes, il faut donner les perms dans le volume avant
    volumes:
      - python_images:/app/Images
    command: 
      sh -c "
        mkdir -p /app/Images &&
        chmod -R 777 /app/Images &&
        chmod -R 777 /app/build
      "



volumes:
  react_build:
  python_images:
    driver: local
    driver_opts: 
      type: none
      device: ./backend/Images
      o: bind